### ISSUE TITLE
Failure on wheel build for TelFit

### ISSUE THREAD

**Issue by gmbrandt** [kgullikson88/Telluric-Fitter#20]
After installing all the dependencies for TelFit and running pip install TelFit (in a fresh virtual environment), the build fails with the traceback below. The error appears to occur after it tries to fetch http://www.as.utexas.edu/~kgulliks/media/data/aerlbl_v12.2_package.tar.gz 

I received the exact same error upon build after trying to pip install on another computer entirely, again in a fresh virtual environment.

From a browser, http://www.as.utexas.edu/~kgulliks/media/data/aerlbl_v12.2_package.tar.gz
no longer exists. If this is responsible for the failed build, is there a permanent place to host this dependency?

It would be great to get this up and running. This package seems very nice.

Traceback:
```
Collecting TelFit
  Using cached https://files.pythonhosted.org/packages/fe/22/6ea8ae3b671d96c349f513aefaed8ac38117a318ba47ca729b2127541683/TelFit-1.3.2.tar.gz
Requirement already satisfied: matplotlib in /home/gmbrandt/envs/telfit/lib/python2.7/site-packages (from TelFit) (2.2.4)
Requirement already satisfied: numpy>=1.6 in /home/gmbrandt/envs/telfit/lib/python2.7/site-packages (from TelFit) (1.16.5)
Requirement already satisfied: scipy>=0.13 in /home/gmbrandt/envs/telfit/lib/python2.7/site-packages (from TelFit) (1.2.2)
Requirement already satisfied: astropy>=0.2 in /home/gmbrandt/envs/telfit/lib/python2.7/site-packages (from TelFit) (2.0.16)
Requirement already satisfied: lockfile in /home/gmbrandt/envs/telfit/lib/python2.7/site-packages (from TelFit) (0.12.2)
Requirement already satisfied: pysynphot>=0.7 in /home/gmbrandt/envs/telfit/lib/python2.7/site-packages (from TelFit) (0.9.14)
Requirement already satisfied: fortranformat in /home/gmbrandt/envs/telfit/lib/python2.7/site-packages (from TelFit) (0.2.5)
Requirement already satisfied: cython in /home/gmbrandt/envs/telfit/lib/python2.7/site-packages (from TelFit) (0.29.14)
Requirement already satisfied: requests in /home/gmbrandt/envs/telfit/lib/python2.7/site-packages (from TelFit) (2.22.0)
Requirement already satisfied: cycler>=0.10 in /home/gmbrandt/envs/telfit/lib/python2.7/site-packages (from matplotlib->TelFit) (0.10.0)
Requirement already satisfied: backports.functools-lru-cache in /home/gmbrandt/envs/telfit/lib/python2.7/site-packages (from matplotlib->TelFit) (1.6.1)
Requirement already satisfied: subprocess32 in /home/gmbrandt/envs/telfit/lib/python2.7/site-packages (from matplotlib->TelFit) (3.5.4)
Requirement already satisfied: kiwisolver>=1.0.1 in /home/gmbrandt/envs/telfit/lib/python2.7/site-packages (from matplotlib->TelFit) (1.1.0)
Requirement already satisfied: pytz in /home/gmbrandt/envs/telfit/lib/python2.7/site-packages (from matplotlib->TelFit) (2019.3)
Requirement already satisfied: six>=1.10 in /home/gmbrandt/envs/telfit/lib/python2.7/site-packages (from matplotlib->TelFit) (1.13.0)
Requirement already satisfied: python-dateutil>=2.1 in /home/gmbrandt/envs/telfit/lib/python2.7/site-packages (from matplotlib->TelFit) (2.8.1)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /home/gmbrandt/envs/telfit/lib/python2.7/site-packages (from matplotlib->TelFit) (2.4.5)
Requirement already satisfied: pytest<3.7,>=2.8 in /home/gmbrandt/envs/telfit/lib/python2.7/site-packages (from astropy>=0.2->TelFit) (3.6.4)
Requirement already satisfied: beautifulsoup4 in /home/gmbrandt/envs/telfit/lib/python2.7/site-packages (from pysynphot>=0.7->TelFit) (4.8.1)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /home/gmbrandt/envs/telfit/lib/python2.7/site-packages (from requests->TelFit) (1.25.7)
Requirement already satisfied: certifi>=2017.4.17 in /home/gmbrandt/envs/telfit/lib/python2.7/site-packages (from requests->TelFit) (2019.11.28)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /home/gmbrandt/envs/telfit/lib/python2.7/site-packages (from requests->TelFit) (3.0.4)
Requirement already satisfied: idna<2.9,>=2.5 in /home/gmbrandt/envs/telfit/lib/python2.7/site-packages (from requests->TelFit) (2.8)
Requirement already satisfied: setuptools in /home/gmbrandt/envs/telfit/lib/python2.7/site-packages (from kiwisolver>=1.0.1->matplotlib->TelFit) (42.0.2)
Requirement already satisfied: py>=1.5.0 in /home/gmbrandt/envs/telfit/lib/python2.7/site-packages (from pytest<3.7,>=2.8->astropy>=0.2->TelFit) (1.8.0)
Requirement already satisfied: more-itertools>=4.0.0 in /home/gmbrandt/envs/telfit/lib/python2.7/site-packages (from pytest<3.7,>=2.8->astropy>=0.2->TelFit) (5.0.0)
Requirement already satisfied: funcsigs; python_version < "3.0" in /home/gmbrandt/envs/telfit/lib/python2.7/site-packages (from pytest<3.7,>=2.8->astropy>=0.2->TelFit) (1.0.2)
Requirement already satisfied: attrs>=17.4.0 in /home/gmbrandt/envs/telfit/lib/python2.7/site-packages (from pytest<3.7,>=2.8->astropy>=0.2->TelFit) (19.3.0)
Requirement already satisfied: atomicwrites>=1.0 in /home/gmbrandt/envs/telfit/lib/python2.7/site-packages (from pytest<3.7,>=2.8->astropy>=0.2->TelFit) (1.3.0)
Requirement already satisfied: pluggy<0.8,>=0.5 in /home/gmbrandt/envs/telfit/lib/python2.7/site-packages (from pytest<3.7,>=2.8->astropy>=0.2->TelFit) (0.7.1)
Requirement already satisfied: soupsieve>=1.2 in /home/gmbrandt/envs/telfit/lib/python2.7/site-packages (from beautifulsoup4->pysynphot>=0.7->TelFit) (1.9.5)
Building wheels for collected packages: TelFit
  Building wheel for TelFit (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/gmbrandt/envs/telfit/bin/python2 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-gZQ8fz/TelFit/setup.py'"'"'; __file__='"'"'/tmp/pip-install-gZQ8fz/TelFit/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-5Ql0BD --python-tag cp27
       cwd: /tmp/pip-install-gZQ8fz/TelFit/
  Complete output (48 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-2.7
  copying src/TelluricFitter.py -> build/lib.linux-x86_64-2.7
  copying src/MakeModel.py -> build/lib.linux-x86_64-2.7
  copying src/DataStructures.py -> build/lib.linux-x86_64-2.7
  copying src/MakeTape5.py -> build/lib.linux-x86_64-2.7
  creating build/lib.linux-x86_64-2.7/telfit
  copying src/telfit/__init__.py -> build/lib.linux-x86_64-2.7/telfit
  running build_ext
  Downloading data from http://www.as.utexas.edu/~kgulliks/media/data/aerlbl_v12.2_package.tar.gz and putting it in directory /home/gmbrandt/.TelFit/
  
  gzip: stdin: not in gzip format
  tar: Child returned status 1
  tar: Error is not recoverable: exiting now
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-gZQ8fz/TelFit/setup.py", line 353, in <module>
      package_dir={'': 'src'}
    File "/home/gmbrandt/envs/telfit/local/lib/python2.7/site-packages/setuptools/__init__.py", line 145, in setup
      return distutils.core.setup(**attrs)
    File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
      dist.run_commands()
    File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
      self.run_command(cmd)
    File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "/home/gmbrandt/envs/telfit/local/lib/python2.7/site-packages/wheel/bdist_wheel.py", line 192, in run
      self.run_command('build')
    File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "/usr/lib/python2.7/distutils/command/build.py", line 128, in run
      self.run_command(cmd_name)
    File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "/tmp/pip-install-gZQ8fz/TelFit/setup.py", line 289, in run
      MakeLBLRTM()
    File "/tmp/pip-install-gZQ8fz/TelFit/setup.py", line 207, in MakeLBLRTM
      subprocess.check_call(['tar', '-xzf', outfile, '-C', TELLURICMODELING])
    File "/usr/lib/python2.7/subprocess.py", line 190, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['tar', '-xzf', '/home/gmbrandt/.TelFit/aerlbl_package.tar.gz', '-C', '/home/gmbrandt/.TelFit/']' returned non-zero exit status 2
  ----------------------------------------
  ERROR: Failed building wheel for TelFit
```

**Comment by kgullikson88** [comment]
Can you try building off the master branch of this repo? I moved the files to zenodo.org, but may not have made a new pip package.

**Comment by gmbrandt** [comment]
Thanks, pip installing with `pip install git+https://github.com/kgullikson88/Telluric-Fitter` resolves the download error. Now I get a compiler error, but I will tinker with that and open a separate issue if it persists.

**Comment by jschiappacasse** [comment]
> Thanks, pip installing with `pip install git+https://github.com/kgullikson88/Telluric-Fitter` resolves the download error. Now I get a compiler error, but I will tinker with that and open a separate issue if it persists.

Hi, 

I got exactly the same error. Could you find any solution?
I have Ubuntu 18.04.3
